apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bareuptime-backend

resources:
  - manifests.yaml      # Core resources: namespace, serviceaccount, pvc, service, deployment
  - secrets.yaml        # Secrets management: secretstore, externalsecrets (7 total)
  - ingress.yaml        # Ingress routes and middlewares

commonLabels:
  app: bareuptime-backend
  environment: production
  managed-by: argocd

# Images to track (for ArgoCD image updater)
images:
  - name: ghcr.io/bareuptime/backend
    newTag: latest
