# ===============================================
# BareUptime Backend - Native Kubernetes Secrets
# ===============================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: bareuptime-backend
  labels:
    app: bareuptime-backend
    environment: production

---
# Persistent storage for application data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: bareuptime-backend
  labels:
    app: bareuptime-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
# GHCR Docker credentials (from native secret)
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: bareuptime-backend
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<>",
          "password": "<"
        }
      }
    }

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bareuptime-backend
  namespace: bareuptime-backend
  labels:
    app: bareuptime-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bareuptime-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: bareuptime-backend
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: ghcr-credentials

      initContainers:
        - name: wait-for-database
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z 10.10.85.1 5432; do echo Waiting for DB; sleep 2; done"]

      containers:
        - name: backend
          image: ghcr.io/bareuptime/backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            # Port configuration
            - name: PORT
              value: "8080"
            - name: GOMAXPROCS
              value: "2"
            - name: GOGC
              value: "100"
            - name: GOMEMLIMIT
              value: "450MiB"

            # Region
            - name: REGION
              value: "falkenstein"
            - name: REGION_TAG
              value: "region=falkenstein"

            # Logging
            - name: LOG_FORMAT
              value: "json"

            - name: APP_ENV
              value: "prod"

            # Redis Sentinel configuration
            - name: REDIS_MASTER_NAME
              value: "mymaster"
            - name: REDIS_SENTINELS
              value: "redis-sentinel-sentinel.common.svc.cluster.local:26379"
            # Application configuration
            - name: APP_ENV
              value: "production"
            - name: APP_NAME
              value: "bareuptime"
            - name: LOG_LEVEL
              value: "info"
            - name: DEFAULT_LANG
              value: "en"
            - name: EMAIL_FROM_ADDRESS
              value: "support@bareuptime.co"
            - name: EMAIL_FROM_NAME
              value: "Suman Saurabh"
            - name: EMAIL_REPLY_TO_ADDRESS
              value: "support@bareuptime.co"
            - name: FRESHDESK_DOMAIN
              value: "bareuptime"
            - name: VAPID_SUBJECT
              value: "mailto:support@bareuptime.co"
            - name: FCM_PROJECT_ID
              value: "bareuptime-co"

            # ClickHouse credentials
            - name: CLICKHOUSE_URLS
              value: "10.10.85.1:9000,10.10.85.5:9000"

            - name: FCM_CREDENTIALS_PATH
              value: "secrets/google-service-account.json"

          envFrom:
            - secretRef:
                name: bareuptime-backend-secrets

          volumeMounts:
            - name: backend-storage
              mountPath: /opt/bareuptime
            - name: google-service-account
              mountPath: /secrets
              readOnly: true

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: 150m
              memory: 365Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-storage
        - name: google-service-account
          secret:
            secretName: google-service-account
            optional: true
            items:
              - key: google-service-account.json
                path: google-service-account.json

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bareuptime-backend
  labels:
    app: bareuptime-backend
spec:
  selector:
    app: bareuptime-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
