apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: bareuptime-backend
  labels:
    app: bareuptime-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
